# 2.2 Data representations for neural networks

## tensors 

### Scalars (0D tensors)

In [6]:
import numpy as np
x = np.array(12)
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

12
rank= 0
shape= ()


### Vectors (1D tensors)

In [7]:
x = np.array([12, 3, 6, 14])
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

[12  3  6 14]
rank= 1
shape= (4,)


### Matrices (2D tensors)

In [8]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
rank= 2
shape= (3, 5)


### 3D tensors and higher-dimensional tensors

In [9]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
               [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
               [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
rank= 3
shape= (3, 3, 5)
