# 2.2 Data representations for neural networks

## tensors 

### Scalars (0D tensors)

In [6]:
import numpy as np
x = np.array(12)
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

12
rank= 0
shape= ()


### Vectors (1D tensors)

In [7]:
x = np.array([12, 3, 6, 14])
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

[12  3  6 14]
rank= 1
shape= (4,)


### Matrices (2D tensors)

In [8]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
rank= 2
shape= (3, 5)


### 3D tensors and higher-dimensional tensors

In [9]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
               [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
               [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
print(x,)
print('rank=',x.ndim)
print('shape=',x.shape)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
rank= 3
shape= (3, 3, 5)


## Element-wise operation
note: Relu ---> element-wise operation
### Broadcasting

In [4]:
import numpy as np
x = np.random.random((5, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)
print (z)

[[[[0.68585957 0.94865427 0.39745956 ... 0.90514365 0.55234971
    0.93456976]
   [0.54828878 0.80114728 0.76721989 ... 0.76965565 0.63246766
    0.56375822]
   [0.33619613 0.95723157 0.1133714  ... 0.56916943 0.48075126
    0.98376059]
   ...
   [0.78061005 0.72654648 0.68094364 ... 0.92326363 0.37938268
    0.70188396]
   [0.81145484 0.89188354 0.22888116 ... 0.86789145 0.84821321
    0.61202605]
   [0.65849813 0.54885937 0.92424804 ... 0.59902091 0.96196553
    0.5912326 ]]

  [[0.68585957 0.74392792 0.40789617 ... 0.53646556 0.5989417
    0.93456976]
   [0.83248157 0.54599555 0.76721989 ... 0.59074816 0.85364093
    0.56375822]
   [0.88224207 0.666352   0.36202922 ... 0.56916943 0.48075126
    0.98376059]
   ...
   [0.9138119  0.72654648 0.68094364 ... 0.91926924 0.56526484
    0.66771557]
   [0.81145484 0.89188354 0.44003665 ... 0.86789145 0.84821321
    0.61202605]
   [0.65849813 0.23219448 0.92424804 ... 0.55805029 0.22449189
    0.67804665]]

  [[0.68585957 0.74392792 0.3974595